services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Alpaka78
      POSTGRES_DB: Matmalab
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d Matmalab -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/root/matmalab_app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./matmalab_app:/root/matmalab_app

